spring.config.import=optional:file:.env[.properties]

server.port=${PORT:8080}
app.admin-setup-key=${ADMIN_SETUP_KEY:}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=false